### ISSUE TITLE
Verify `getDesc` is returned by `getUnitDescriptor`

### ISSUE THREAD

**Issue by justin-lovell** [DCS-gRPC/rust-server#123]
https://github.com/DCS-gRPC/rust-server/blob/15f806463cc7df23ac9c73d67c90fa0a8dbc1d76/lua/DCS-gRPC/methods/unit.lua#L112-L114

Table is populated with index values, but not with any **values** or **keys**.

**Comment by rurounijones** [comment]
The `Attributes` section of the getDesc is just a list. You can see here: https://wiki.hoggitworld.com/view/DCS_func_getDesc that every attribute is the key with the name and the value with `true`. Returning this as a list make more sense than the lua datastructure.

**Comment by justin-lovell** [comment]
Cheers, I was a bit perplexed about the "shape" of the API and I was making a bookmarklet to get back to it.
