### ISSUE TITLE
Connection refused after a couple of hours

### ISSUE THREAD

**Issue by marvinpolinowski** [DCS-gRPC/rust-server#128]
Hello!

I am having the following problem after the server was running for a couple of hours:

Copied the log out of the Air defense logging, but my own application gets the same error. 
Could it be that I did not properly close the connection i.e when forcefully shutting down my debugging session in Visual Studio?
I have a session pool that only allows one active session at a time so it cannot be that too many sessions are created.

I will have a look if there is a difference between me shutting it down using the ShutdownAsync function and forcefully closing and will list the results here.

Many thanks in advance!

IP replaced with ***

Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.  = Connection refused by the remote host.

[WRN] gRPC Exception
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (***) SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.", DebugException="System.Net.Http.HttpRequestException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (***)
 ---> System.Net.Sockets.SocketException (10061): Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

**Comment by marvinpolinowski** [comment]
Probably my bad, created new NetClients every couple of minutes. Thought I'd only have to pool the initial channel. Seems to run fine, for now, will continue monitoring!

**Comment by rurounijones** [comment]
Hola!

With `AirDefenseLogging` do you mean the `SimpleAirDefence` application?

If yes. Could you confirm if you think that the `SimpleAirDefence` application was having the issue where it could not connect after a few hours? Or was that related to how you were closing it in VisualStudio do you think? I don't think I ever ran it for hours so it could be a bug in there.

**Comment by rurounijones** [comment]
No followup comments so based on the previous comment I think things should be fine. Closing.
