### ISSUE TITLE
Don't return errors from Rust to Lua

### ISSUE THREAD

**Issue by rkusa** [DCS-gRPC/rust-server#138]
It looks like errors returned from Rust to Lua might lead to DCS crashing once a mission is stopped. So either figure out what is wrong with those errors, or don't return errors at all and simply log them with `log::error!` instead.

**Comment by rkusa** [comment]
Actually, this seems to be only related to the hot reloading of the dll module. So only relevant for development. The cause being some lifetime/ownership issues of the returned error when between passed between the hot reloading dll and the normal dll.

**Comment by rurounijones** [comment]
If this only happens in hot_loading mode then I am fine with continuing to return errors to lua so that they can be written to the `dcs.log`

**Comment by rkusa** [comment]
@rurounijones I am unsure if I am just unable to reproduce it without the hot reloading. Maybe we should merge https://github.com/DCS-gRPC/rust-server/pull/150 and see if Enigma's crash is gone, and if not, revert the PR again?

**Comment by rurounijones** [comment]
@rkusa I will create a DCS-gRPC build for Enigma specifically and deploy it on to their server and then we will probably have to wait for a while (a few weeks at least, maybe a month) since the crash was very rare.

If it doesn't crash within that time then I think we can say that it is worth merging.

**Comment by rkusa** [comment]
@rurounijones Sounds good 👍

**Comment by rurounijones** [comment]
Closing as no newly reported issues
