### ISSUE TITLE
GetSessionId API

### ISSUE THREAD

**Issue by rurounijones** [DCS-gRPC/rust-server#143]
Since DCS-gRPC clients have a lifecycle outside of the DCS server we need a way for them to know if a mission has restarted or a new one loaded. At the moment the only thing a client will know is that it got disconnected and then reconnected.

After bouncing some ideas around with @rkusa I think what we want is:

1. Implement a `Mission.GetSessionId` (Namespace up for debate) `DCS-gRPC` method.
2. When called it checks for the existance of a DCS userFlag `dcs_grpc_session_id`
3. If no value exists then set the value to the current unixtime (since flags can only contain bool or numeric) using something like `os.time(os.date("!*t"))` and return the value.
4. If a value exists then return the existing value.

This will generate a new session unique ID each time a mission is loaded and return the same value until another one is loaded. Clients can then use this ID to determine if a session has changed after getting disconnected and perform appropriate processing.

Documenting this here in case anyone wants to give it a go, otherwise I will get around to it at some point. This would be a good, simple, API to implement for a newcomer.

**Comment by rkusa** [comment]
> 3. If no value exists then set the value to the current unixtime (since flags can only contain bool or numeric) using something like `os.time(os.date("!*t"))` and return the value.

Alternatively, the unixtime could also be retrieved inside of the Rust part of the implementation via [OffsetDateTime::unix_timestamp](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#method.unix_timestamp). This way, there wouldn't be any additional Lua part necessary for this feature, as one could simply re-use the existing lua methods for `GetUserFlag`/`SetUserFlag` from Rust.

**Comment by justin-lovell** [comment]
The selection issue of the `UserFlag` number might be a problem (never know about a conflict?)

You could probably just store this as a start-up variable (initialized `OffsetDateTime::unix_timestamp`) within Rust and just return it directly? No need to jump down into the mission environment.

If the mission ends and starts a new one, reset could be triggered with `handler.onMissionLoadEnd()` chain.

**Comment by rurounijones** [comment]
Implemented by @vivanov
