### ISSUE TITLE
DCS-gRPC server never starts listening

### ISSUE THREAD

**Issue by RobCollie** [DCS-gRPC/rust-server#185]
Hi ya'll, using the latest version it looks like the server never starts. The only mention in the log is:

2022-10-03 09:56:22.708 INFO    [GRPC-Hook]: Initializing ...
2022-10-03 09:56:22.708 INFO    [GRPC-Hook]: Checking optional config at `Config/dcs-grpc.lua` ...
2022-10-03 09:56:22.708 INFO    [GRPC-Hook]: `Config/dcs-grpc.lua` successfully read
2022-10-03 09:56:22.710 INFO    [GRPC-Hook]: Initialized ...

There is no gRPC.log being generated.  Our dcs_grpc.lua is as follows:

autostart = true
-- Whether the `Eval` method is enabled or not.
evalEnabled = false

-- The host the gRPC listens on (use "0.0.0.0" to listen on all IP addresses of the host).
host = '0.0.0.0'

-- The port to listen on.
port = 50052

-- Whether debug logging is enabled or not.
debug = true

-- Limit of calls per second that are executed inside of the mission scripting environment.
throughputLimit = 600

**Comment by rurounijones** [comment]
Have you added the line that includes DCS-gRPC to your `MissionScripting.lua` file in the DCS installation `Scripts` directory?

**Comment by RobCollie** [comment]
dofile('Scripts/ScriptingSystem.lua')
dofile(lfs.writedir()..[[Scripts\DCS-gRPC\grpc-mission.lua]])

Second line in. It's very odd.

**Comment by RobCollie** [comment]
I feel like I've been through every lua file, every log and nothing seems amiss. Yet, it's not listening.

**Comment by rkusa** [comment]
No `[GRPC]` entries at all in `dcs.log` sounds a lot like `grpc-mission.lua` isn't loaded (not even tried loading). Since you have the line in the `MissionScripting.lua`, can you confirm that `Saved Games\DCS.openbeta_server\Scripts\DCS-gRPC\DCS-gRPC\grpc-mission.lua` exists?

**Comment by RobCollie** [comment]
2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Initializing ...
2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Checking optional config at Config/dcs-grpc.lua ...
2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Config/dcs-grpc.lua successfully read
2022-10-03 09:56:22.710 INFO [GRPC-Hook]: Initialized ...

Is the log, so something loads.

Scripts\DCS-gRPC\grpc-mission.lua does exist.

So, I presume if it was loading, the following would log to the dcs.log?

 env.info("[GRPC] Checking optional config at `Config/dcs-grpc.lua` ...")

**Comment by rkusa** [comment]
> 2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Initializing ... 2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Checking optional config at Config/dcs-grpc.lua ... 2022-10-03 09:56:22.708 INFO [GRPC-Hook]: Config/dcs-grpc.lua successfully read 2022-10-03 09:56:22.710 INFO [GRPC-Hook]: Initialized ...
> 
> Is the log, so something loads.

Yes, those logs confirm that `Saved Games\DCS.openbeta_server\Scripts\Hooks\DCS-gRPC.lua` is installed correctly.

> Scripts\DCS-gRPC\grpc-mission.lua does exist.
> 
> So, I presume if it was loading, the following would log to the dcs.log?
> 
> env.info("[GRPC] Checking optional config at `Config/dcs-grpc.lua` ...")

Yes, this is the first expected log. Can you share your whole `dcs.log`?

**Comment by RobCollie** [comment]
Sure, here it is:

[dcs.log](https://github.com/DCS-gRPC/rust-server/files/9710026/dcs.log)

**Comment by rkusa** [comment]
@RobCollie Thanks for sharing. I couldn't spot anything that looks like it could be messing with the gRPC script. I am running out of ideas. The only thing worth testing that comes to my mind right now would be to reset the `MissionScripting.lua` to its original form and only make the modifications necessary for the gRPC (assuming you might have other changes/additions in there).

**Comment by RobCollie** [comment]
No worries. It's an odd one, right? 

I'll revert the MissionScripting.lua and see.

**Comment by rurounijones** [comment]
If you can jump on the OverlordBot Discord at some point and do a screenshare we may be able to go through it together

**Comment by RobCollie** [comment]
Sounds good to me. Tomorrow sometime?

**Comment by rurounijones** [comment]
Ping me in the Discord and if I am around; we can go through it

**Comment by rurounijones** [comment]
Mission scripting.lua was being replaced by SLMod
