### ISSUE TITLE
Add SRS client connected/disconnected/freq-changed events

### ISSUE THREAD

**Issue by rkusa** [DCS-gRPC/rust-server#201]
Since we have an SRS integration now, we could establish an SRS Connection that listens for SRS events and broadcasts them on the gRPC event stream.

Possible events might be:
- Client connected
- Client disconnnected
- Client frequency changed

I am not sure if the mapping from an SRS client to a unit works well enough. I know that we are getting the unit id, but finding a unit just by its id is a mess (there is no `getById`).

**Comment by rurounijones** [comment]
This would be exceedingly useful but would require a permanent connection to the SRS server if I remember correctly, which we are currently not doing.

For getting the unit, depending on where the ID is coming from, [LoGetObjectById](https://github.com/sprhawk/dcs_scripts/blob/master/Export.lua#L391) might work.

Another option suggested is:

> kukiric: those export IDs are equivalent to the id_ field in every DCS mission object, and you can construct a new object in the mission environment with that ID by creating a table with that property, and using the proper class methods ie. local unit = { id_ = 123456 }; Unit.getName(unit)
