### ISSUE TITLE
Add group information to unit-stream

### ISSUE THREAD

**Issue by rkusa** [DCS-gRPC/rust-server#21]
See:
- https://github.com/DCS-gRPC/rust-server/pull/11#issuecomment-890723201
- https://github.com/DCS-gRPC/rust-server/pull/11#issuecomment-903250992
- https://github.com/DCS-gRPC/rust-server/pull/11#issuecomment-903350183

**Comment by rurounijones** [comment]
As part of this, added `groupName` field to the unit object in https://github.com/DCS-gRPC/rust-server/commit/9df9e01ca47f6227e491d5cd80d7c746599409eb
