### ISSUE TITLE
MarkAdd and MarkChange event payload arrives without mark position

### ISSUE THREAD

**Issue by mobot-gh** [DCS-gRPC/rust-server#219]
### Issue:
Event payloads for MarkAdd and MarkChange arrive without the position of the mark. Text is also missing from MarkAdd event payloads associated with player-created marks but this is expected as the player places the mark and then accesses the text field to add a text label, if any, leading to a text-less MarkAdd and then a MarkChange event with text.

### Relevant source code
[MarkAdd Event](https://github.com/DCS-gRPC/rust-server/blob/921bc5346f14dd0529a94ba1d73a242b5c158689/lua/DCS-gRPC/methods/mission.lua#L280)
[MarkChange Event](https://github.com/DCS-gRPC/rust-server/blob/921bc5346f14dd0529a94ba1d73a242b5c158689/lua/DCS-gRPC/methods/mission.lua#L298)

### Steps to reproduce:
 - Parse the event stream for MarkAdd or MarkChange events.
 - Log the MarkAdd or MarkChange event response object.
 
 ### Code snippet
 ```
 public async Task StreamEventsAsync(CancellationToken stoppingToken)
        {
            using var channel = GrpcChannel.ForAddress($"http://{HostName}:{Port}");
            var client = new MissionService.MissionServiceClient(channel);
            try
            {
                var events = client.StreamEvents(new StreamEventsRequest(), null, null, stoppingToken);
                await foreach (var e in events.ResponseStream.ReadAllAsync(stoppingToken))
                {
                    switch (e.EventCase)
                    {
                        case StreamEventsResponse.EventOneofCase.MarkAdd:
                            var newMark = e.MarkAdd;
                            _logger.LogDebug("Adding a new mark - {mark}", newMark);
```

### Result
```
{
	"initiator": {
		"unit": {
			"id": 7783,
			"name": "BLUE_20_ROAD F-5 3-1",
			"callsign": "Springfield31",
			"coalition": "COALITION_BLUE",
			"type": "F-5E-3",
			"position": {
				"lat": 43.81734132061216,
				"lon": 41.89413983212559,
				"alt": 5627.6572265625,
				"u": 615860.2870085243,
				"v": -107926.9034416082
			},
			"orientation": {
				"heading": 96.75879545823936,
				"yaw": 102.99829985943602,
				"pitch": 1.3444178260566746,
				"roll": -4.378423052955361,
				"forward": {
					"x": -0.11765745282173157,
					"y": 0.023462364450097084,
					"z": 0.9927771091461182
				},
				"right": {
					"x": -0.9899398684501648,
					"y": 0.07634354382753372,
					"z": -0.11912543326616287
				},
				"up": {
					"x": 0.07858707010746002,
					"y": 0.9968054890632629,
					"z": -0.014243940822780132
				}
			},
			"velocity": {
				"heading": 96.44647911365011,
				"speed": 260.8526971622145,
				"velocity": {
					"x": -29.287250518798828,
					"y": -2.074129819869995,
					"z": 259.203369140625
				}
			},
			"playerName": "Proton 1-2 | mobot",
			"group": {
				"id": 5575,
				"name": "BLUE_20_ROAD F-5 7",
				"coalition": "COALITION_BLUE",
				"category": "GROUP_CATEGORY_AIRPLANE"
			},
			"numberInGroup": 1
		}
	},
	"coalition": "COALITION_BLUE",
	"id": 251658370
}
```
It is possible of course that DCS has changed the event.

**Comment by mobot-gh** [comment]
As `GRPC.exporters.position` is also called by several other methods including  [GRPC.methods.getUnitPosition](https://github.com/DCS-gRPC/rust-server/blob/921bc5346f14dd0529a94ba1d73a242b5c158689/lua/DCS-gRPC/methods/unit.lua#L49) & [GRPC.exporters.markPanel](https://github.com/DCS-gRPC/rust-server/blob/921bc5346f14dd0529a94ba1d73a242b5c158689/lua/DCS-gRPC/exporters/object.lua#L113), and I have used these two without issue, it adds more weight to the possibility that the `event.pos` field is either, not be being sent by DCS, or sent in an unexpected format for the `S_EVENT_MARK_ADDED` and `S_EVENT_MARK_CHANGED` events. 

Could `coord.LOtoLL` be guarding against an exception and returning nil and then the `payload.pos` field is dropped when serialised?

**Comment by rurounijones** [comment]
Note that the `GetMarkPanels` API works correctly.

```
    {
      "id": 101,
      "time": 43204,
      "coalition": "COALITION_BLUE",
      "groupId": 4294967295,
      "text": "SAM - 2-25 AVN, BCO, 2nd FLT",
      "position": {
        "lat": 44.6036699254733,
        "lon": 39.39183352228041,
        "alt": 206.00123596191406,
        "u": 407732.53125,
        "v": -39280.46484375
      }
    }
```

**Comment by rurounijones** [comment]
Looksl ike this is fixed by https://github.com/DCS-gRPC/rust-server/pull/221
