### ISSUE TITLE
grpcurl  Too Many Arguments

### ISSUE THREAD

**Issue by fsverse** [DCS-gRPC/rust-server#262]
Not sure if it's a bug but ...

grpcurl.exe -plaintext -import-path ./protos -proto ./protos/dcs/dcs.proto -d '{\"text\": \"Works!\", \"display_time\": 10, \"clear_view\": false}' 127.0.0.1:50051 dcs.trigger.v0.TriggerService/OutText

doesn't work (on windows 10 in Command Prompt).

The single quotes around the json seem to be the issue. Replaced them with double quotes and now it seems fine.

grpcurl.exe -plaintext -import-path ./protos -proto ./protos/dcs/dcs.proto -d "{\"text\": \"Works!\", \"display_time\": 10, \"clear_view\": false}" 127.0.0.1:50051 dcs.trigger.v0.TriggerService/OutText

Hopefully this saves someone a bit of time.

**Comment by rurounijones** [comment]
https://github.com/DCS-gRPC/rust-server/commit/3d05d601b3c89ae5c80377988bf287ecb31b23ce
