### ISSUE TITLE
Get Map/Mission name

### ISSUE THREAD

**Issue by rurounijones** [DCS-gRPC/rust-server#79]
* A lot of client logic is tied up in what map is currently loaded. 
* More advanced usage may also have specific logic running depending on the mission name (e.g. if someone writes a client that basically runs a mission).

Therefore we should make it easy to retrieve the map and mission name via DCS-gRPC.

**Comment by rkusa** [comment]
You can already get the mission name: https://github.com/DCS-gRPC/rust-server/blob/main/protos/dcs/hook/v0/hook.proto#L6-L7

**Comment by rurounijones** [comment]
Whoops, well that is one less thing to implement :grin:

**Comment by rurounijones** [comment]
Someone pointed out that one way to get the map name is search for a known airfield on each map and then return the map if the airfield is found. I will probably implement it this way until a better solution presents itself.

**Comment by rurounijones** [comment]
`env.mission.theatre` returns the map name so we can use that.

**Comment by rurounijones** [comment]
Map name (Theatre) covered by https://github.com/DCS-gRPC/rust-server/pull/142
